package by.training.pharmacy.dao.impl.database;

/**
 * Created by vladislav on 20.06.16.
 */
public class DatabaseDAOTestConstant {
    public static final String CLASS_NAME = "Витамины";
    public static final String CLASS_NAME_2 = "Противовоспалительное";
    public static final String CLASS_DESCRIPTION = "Показано при кровотечениях и открытых переломах";
    public static final String CLASS_NAME_3 = "Анальгетик";
    public static final String CLASS_NAME_4 = "Что-то другое";
    public static final String CLASS_DESCRIPTION_2 = "Данный тип лекарств устарел=)";
    public static final String DATABASE_URL = "jdbc:mysql://localhost:3306/online_pharmacy?characterEncoding=UTF-8";
    public static final String DATABASE_USER = "root";
    public static final String DATABASE_PASSWORD = "root";
    public static final String GET_DRUG_CLASS_BY_NAME_QUERY = "SELECT dr_class_name, dr_class_description FROM drug_classes WHERE dr_class_name=?";
    public static final int ID_1 = 1;
    public static final int ID_6 = 6;
    public static final int LIMIT = 10;
    public static final int START_FROM = 0;
    public static final String DRUG_NAME = "ок";
    public static final String GET_DRUGS_BY_NAME_QUERY = "SELECT dm_id,  dr_id, dr_class, dr_description, dr_image, dr_in_stock, dr_manufacturer, dr_name, dr_prescription_enable, dr_price, dr_type,  dr_dosage, dr_active_substance, dm_name, dm_country, dm_description, dr_class_name, dr_class_description FROM drugs inner join drugs_manufactures on dr_manufacturer = dm_id inner join drug_classes on dr_class = dr_class_name WHERE dr_name LIKE ? LIMIT ?, ?;";
    public static final String GET_DRUGS_BY_CLASS_QUERY = "SELECT dm_id, dr_id,  dr_class, dr_description, dr_image, dr_in_stock, dr_manufacturer, dr_name, dr_prescription_enable, dr_price, dr_type,  dr_dosage, dr_active_substance, dm_name, dm_country, dm_description, dr_class_name, dr_class_description FROM drugs inner join drugs_manufactures on dr_manufacturer = dm_id inner join drug_classes on dr_class = dr_class_name WHERE dr_class=? LIMIT ?, ?;";
    public static final String GET_DRUGS_BY_ACTIVE_SUBSTANCE_QUERY  = "SELECT dm_id, dr_id, dr_class, dr_description, dr_image, dr_in_stock, dr_manufacturer, dr_name, dr_prescription_enable, dr_price, dr_type,  dr_dosage, dr_active_substance, dm_name, dm_country, dm_description, dr_class_name, dr_class_description FROM drugs inner join drugs_manufactures on dr_manufacturer = dm_id inner join drug_classes on dr_class = dr_class_name WHERE dr_active_substance=? LIMIT ?, ?;";
    public static final String ACTIVE_SUBSTANCE_NAME = "Морфий";
    public static final String CLASS_NAME_5 = "Антибиотик";
    public static final String CLASS_DESCRIPTION_3 = "Химическое вещество, образуемое микроорганизм";
    public static final String CLASS_NAME_6 = "Название";
    public static final String CLASS_DESCRIPTION_4 = "Описание";
    public static final int DRUG_DOSAGE_1 = 350;
    public static final int DRUG_DOSAGE_2 = 400;
    public static final int MANUFACTURER_ID = 2;
    public static final String MANUFACTURER_NAME = "BAYER";
    public static final String MANUFACTURER_COUNTRY = "Германия";
    public static final String MANUFACTURER_DESCRIPTION = "немецкая химическая и фармацевтическая компания, основанная в Бармене (на данный момент — часть Вупперталя, Германия) в 1863 году. Её штаб-квартира находится в Леверкузене, Северный Рейн — Вестфалия (";
    public static final float DRUG_PRICE = (float) 3.20;
    public static final String GET_DRUG_BY_ID_QUERY = "SELECT dr_id, dm_id, dr_class, dr_description, dr_image, dr_in_stock, dr_manufacturer, dr_name, dr_prescription_enable, dr_price, dr_type,  dr_dosage, dr_active_substance, dm_name, dm_country, dm_description, dr_class_name, dr_class_description FROM drugs inner join drugs_manufactures on dr_manufacturer = dm_id inner join drug_classes on dr_class = dr_class_name WHERE dr_id=?;";
    public static final String GET_MANUFACTURES_BY_COUNTRY_QUERY = "select dm_id, dm_name, dm_country, dm_description from drugs_manufactures where dm_country=? LIMIT ?, ?";
    public static final String MANUFACTURER_COUNTRY_2 = "Беларусь";
    public static final String GET_MANUFACTURES_BY_NAME_QUERY = "select dm_id, dm_name, dm_country, dm_description from drugs_manufactures where dm_name LIKE ? LIMIT ?, ?";
    public static final String MANUFACTURER_NAME_2 = "преп";
    public static final String MANUFACTURER_COUNTRY_3 = "Колумбия";
    public static final String MANUFACTURER_NAME_3 = "qwert";
    public static final String GET_MANUFACTURER_BY_ID_QUERY = "select dm_id, dm_name, dm_country, dm_description from drugs_manufactures where dm_id=? LIMIT 1;";
    public static final String USER_LOGIN = "brovar2012";
    public static final String GET_USERS_ORDERS_QUERY = "SELECT us_login, us_first_name, us_second_name, dr_id, dr_name, or_id, or_drug_count, or_drug_dosage, or_status, or_date from orders inner join users on us_login = or_client_login inner join drugs on dr_id = or_drug_id where or_client_login=? LIMIT ?, ?;";
    public static final String GET_ORDERS_BY_DRUG_ID_QUERY = "SELECT us_login, us_first_name, us_second_name, dr_id, dr_name, or_id, or_drug_count, or_drug_dosage, or_status, or_date from orders inner join users on us_login = or_client_login inner join drugs on dr_id = or_drug_id where or_drug_id=? LIMIT ?, ?;";
    public static final int ID_4 = 4;
    public static final int ID_645 = 645;
    public static final String GET_ORDER_BY_ID_QUERY = "SELECT us_login, us_first_name, us_second_name, dr_id, dr_name, or_id, or_drug_count, or_drug_dosage, or_status, or_date from orders inner join users on us_login = or_client_login inner join drugs on dr_id = or_drug_id where or_id=? LIMIT 1;";
    public static final String GET_USER_PRESCRIPTIONS_QUERY = "select cl.us_login, dr_id, pr_doctor, pr_drug_count, pr_drug_dosage, pr_appointment_date, pr_expiration_date, dr_name, cl.us_first_name, cl.us_second_name, doc.us_first_name as doc_first_name, doc.us_second_name as doc_second_name, doc.us_login as doc_login  from prescriptions inner join drugs on dr_id = pr_drug_id inner join users as cl on pr_client_login = cl.us_login inner join users as doc on pr_doctor = doc.us_login where pr_client_login=? limit ?, ?;";
    public static final String GET_PRESCRIPTIONS_BY_DRUG_ID_QUERY = "select cl.us_login, dr_id, pr_doctor, pr_drug_count, pr_drug_dosage, pr_appointment_date, pr_expiration_date, dr_name, cl.us_first_name, cl.us_second_name, doc.us_first_name as doc_first_name, doc.us_second_name as doc_second_name, doc.us_login as doc_login  from prescriptions inner join drugs on dr_id = pr_drug_id inner join users as cl on pr_client_login = cl.us_login inner join users as doc on pr_doctor = doc.us_login where pr_drug_id=? limit ?, ?;";
    public static final int ID_8 = 8;
    public static final String USER_LOGIN_2 = "vladikxd4";
    public static final String USER_FIRST_NAME = "Владислав";
    public static final String USER_SECOND_NAME = "Завадский";
    public static final String GET_USER_REQUESTS_QUERY = "select cl.us_login, dr_id, re_doctor, re_id, re_prolong_to, re_request_date, re_clients_comment, re_doctors_comment, dr_name, cl.us_first_name, cl.us_second_name, doc.us_first_name as doc_first_name, doc.us_second_name as doc_second_name, doc.us_login as doc_login  from requests_for_prescriptions inner join drugs on dr_id = re_drug_id inner join users as cl on re_client_login = cl.us_login inner join users as doc on re_doctor = doc.us_login WHERE re_client_login=? LIMIT ?, ?;";
    public static final String GET_REQUESTS_BY_DRUG_ID = "select cl.us_login, dr_id, re_doctor, re_id, re_prolong_to, re_request_date, re_clients_comment, re_doctors_comment, dr_name, cl.us_first_name, cl.us_second_name, doc.us_first_name as doc_first_name, doc.us_second_name as doc_second_name, doc.us_login as doc_login  from requests_for_prescriptions inner join drugs on dr_id = re_drug_id inner join users as cl on re_client_login = cl.us_login inner join users as doc on re_doctor = doc.us_login WHERE re_drug_id=? LIMIT ?, ?;";
    public static final int ID_3 = 3;
    public static final String GET_REQUESTS_BY_STATUS_QUERY = "select cl.us_login, dr_id, re_doctor, re_id, re_prolong_to, re_request_date, re_clients_comment, re_doctors_comment, dr_name, cl.us_first_name, cl.us_second_name, doc.us_first_name as doc_first_name, doc.us_second_name as doc_second_name, doc.us_login as doc_login  from requests_for_prescriptions inner join drugs on dr_id = re_drug_id inner join users as cl on re_client_login = cl.us_login inner join users as doc on re_doctor = doc.us_login WHERE re_status=? LIMIT ?, ?;";
    public static final String GET_REQUEST_BY_ID_QUERY = "select cl.us_login, dr_id, re_doctor, re_id, re_prolong_to, re_request_date, re_clients_comment, re_doctors_comment, dr_name, cl.us_first_name, cl.us_second_name, doc.us_first_name as doc_first_name, doc.us_second_name as doc_second_name, doc.us_login as doc_login  from requests_for_prescriptions inner join drugs on dr_id = re_drug_id inner join users as cl on re_client_login = cl.us_login inner join users as doc on re_doctor = doc.us_login WHERE re_id=? LIMIT 1;";
    public static final int ID_5 = 5;
    public static final String USER_LOGIN_3 = "vit.garl";
    public static final String USER_DESCRIPTION = "Описание пользователя";
    public static final String USER_SPECIALIZATION = "Спецеализация пользователя";
    public static final String GET_USER_DESCRIPTION_BY_LOGIN_QUERY = "SELECT sd_user_login, sd_specialization, sd_description FROM staff_descriptions WHERE sd_user_login=? limit 1;";
    public static final String USER_LOGIN_4 = "vadim.sadovski";
    public static final String USER_DESCRIPTION_2  = "Уволен за халатность";
    public static final String USER_PASSWORD = "qwerty";
    public static final String USER_AUTHENTICATON_QUERY = "select us_first_name, us_second_name, us_image, us_mail, us_phone, us_group from users WHERE  us_login=? and us_password=md5(?);";
    public static final String GET_USER_BY_LOGIN_QUERY = "SELECT us_first_name, us_second_name, us_group, us_mail, us_phone, us_image, sd_specialization, sd_description FROM users LEFT JOIN staff_descriptions ON users.us_login = staff_descriptions.sd_user_login WHERE us_login=?;";
    public static final String SEARCH_USERS_BY_ROLE_QUERY = "SELECT us_first_name, us_second_name, us_mail, us_phone, us_image, sd_specialization, sd_description FROM users LEFT JOIN staff_descriptions ON us_login=sd_user_login WHERE us_group=? LIMIT ?, ?;";
    public static final String USER_SPECIALIZATION_2 = "Офтальмолог";
    public static final String GET_USER_BY_SPECIALIZATION_QUERY = "SELECT us_first_name, us_second_name, us_image, us_group, us_mail, us_phone sd_specialization, sd_description FROM users INNER JOIN staff_descriptions ON users.us_login = staff_descriptions.sd_user_login WHERE sd_specialization=? LIMIT ?, ?;";
    public static final String USER_SECOND_NAME_2 = "ски";
    public static final String USER_FIRST_NAME_2 = "адисл";
    public static final String SEARCH_USER_BY_NAME_QUERY = "select us_first_name, us_second_name, us_image, us_mail, us_phone, us_group, sd_specialization, sd_description from users LEFT JOIN staff_descriptions on sd_user_login=us_login where us_first_name LIKE ? and us_second_name LIKE ? LIMIT ?, ?;";
    public static final String USER_PASSWORD_2 = "zxcvbn";
    public static final String USER_LOGIN_5 = "vladislav.zavadski99911123qq";
    public static final String USER_FIRST_NAME_3 = "Иван";
    public static final String USER_SECOND_NAME_3 = "Иванов";
    public static final String USER_LOGIN_6 = "andrei_leshkevich";
    public static final String GET_PRESCRIPTION_BY_DOCTOR = "select cl.us_login, dr_id, re_doctor, re_id, re_prolong_to, re_request_date, re_clients_comment, re_doctors_comment, dr_name, cl.us_first_name, cl.us_second_name, doc.us_first_name as doc_first_name, doc.us_second_name as doc_second_name, doc.us_login as doc_login  from requests_for_prescriptions inner join drugs on dr_id = re_drug_id inner join users as cl on re_client_login = cl.us_login inner join users as doc on re_doctor = doc.us_login WHERE re_doctor=? LIMIT ?, ?;";
}
